// ============================================================
// КОНФИГУРАЦИЯ ИГРЫ
// ============================================================

// Качества предметов
const QUALITIES = {
    'Рваное': { color: '#666', short: 'рван.', multiplier: 0.4, emoji: '🟫' },
    'Плохое': { color: '#999', short: 'плох.', multiplier: 0.6, emoji: '⚪' },
    'Обычное': { color: '#ccc', short: 'обыч.', multiplier: 1.0, emoji: '⬜' },
    'Хорошее': { color: '#8bc34a', short: 'хор.', multiplier: 1.3, emoji: '🟩' },
    'Качественное': { color: '#2196f3', short: 'кач.', multiplier: 1.7, emoji: '🟦' },
    'Мастерское': { color: '#9c27b0', short: 'маст.', multiplier: 2.2, emoji: '🟪' },
    'Легендарное': { color: '#ff9800', short: 'легенд.', multiplier: 2.8, emoji: '🟧' },
    'Мифическое': { color: '#ffd700', short: 'миф.', multiplier: 3.5, emoji: '🌟' }
};

// Национальности
const NATIONALITIES = {
    'Северные земли': { strength:10, cunning:0, defense:5, diplomacy:0 },
    'Речные земли': { strength:0, cunning:10, defense:0, diplomacy:5 },
    'Долина': { strength:0, cunning:0, defense:10, diplomacy:5 },
    'Западные земли': { strength:0, cunning:5, defense:0, diplomacy:10 },
    'Простор': { strength:0, cunning:0, defense:0, diplomacy:10 },
    'Штормовые земли': { strength:10, cunning:5, defense:0, diplomacy:0 },
    'Дорн': { strength:0, cunning:10, defense:5, diplomacy:0 }
};

// Здания (локации)
const BUILDINGS = [
    { id:'Таверна', label:'🍺 Таверна' },
    { id:'Рынок', label:'🏪 Рынок' },
    { id:'Кузница', label:'⚒️ Кузница' },
    { id:'Оружейная лавка', label:'🗡️ Оружейная лавка' },
    { id:'Кожевник', label:'🪡 Кожевник' },
    { id:'Бронник', label:'🛡️ Бронник' },
    { id:'Плотник', label:'🪵 Плотник' },
    { id:'Конюшня', label:'🐴 Конюшня' },
    { id:'Гильдия торговцев', label:'🏛️ Гильдия торговцев' },
    { id:'Магистрат', label:'📜 Магистрат' },
    { id:'Ворота', label:'🚪 Ворота' },
    { id:'Королевский квартал', label:'👑 Королевский квартал' },
    { id:'Торговый квартал', label:'🏙️ Торговый квартал' },
    { id:'Квартал бедноты', label:'🏚️ Квартал бедноты' },
    { id:'Дом', label:'🏠 Дом' },
    { id:'Великая септа', label:'⛪ Великая септа' },
    { id:'Порт', label:'⛵ Порт' },
    { id:'Тюрьма', label:'⛓️ Тюрьма' },
    { id:'Дорога', label:'🛤️ Дорога' },
    { id:'Библиотека мейстеров', label:'📚 Библиотека мейстеров' },
    { id:'Гильдия наёмников', label:'🗡️ Гильдия наёмников' },
    { id:'Бордель', label:'💃 Бордель' }
];

// Уровни локаций
const LOCATION_LEVELS = {
    'Таверна':1,'Рынок':1,'Кузница':1,'Оружейная лавка':1,'Кожевник':1,'Бронник':1,
    'Плотник':1,'Конюшня':1,'Гильдия торговцев':1,'Магистрат':1,
    'Ворота':1,
    'Королевский квартал':1,'Торговый квартал':1,'Квартал бедноты':1,'Дом':1,
    'Великая септа':1,'Порт':1,'Тюрьма':1,
    'Дорога':5,
    'Библиотека мейстеров':1,
    'Гильдия наёмников':1,
    'Бордель':1
};

// Типы жилья
const HOUSING_TYPES = {
    'night': { name: 'Ночлежка', district: 'Квартал бедноты', price: 30, rent: 3, storageSlots: 10, restHp: 10, restFatigue: 10, bonusInt: 0, bonusLuck: -1, bonusDef: 0, emoji: '🏚️', description: 'Общая комната. Дешево, но шумно.' },
    'room': { name: 'Комната', district: 'Торговый квартал', price: 120, rent: 8, storageSlots: 20, restHp: 20, restFatigue: 20, bonusInt: 1, bonusLuck: 0, bonusDef: 0, emoji: '🏠', description: 'Скромная комната с кроватью, столом и шкафом.' },
    'house': { name: 'Дом', district: 'Торговый квартал', price: 400, rent: 20, storageSlots: 40, restHp: 35, restFatigue: 35, bonusInt: 2, bonusLuck: 0, bonusDef: 1, emoji: '🏡', description: 'Собственный дом с садом, подвалом и чердаком.' },
    'townhouse': { name: 'Таунхаус', district: 'Королевский квартал', price: 800, rent: 35, storageSlots: 60, restHp: 50, restFatigue: 50, bonusInt: 3, bonusLuck: 1, bonusDef: 2, emoji: '🏘️', description: 'Двухэтажный дом в престижном районе.' },
    'mansion': { name: 'Особняк', district: 'Королевский квартал', price: 2000, rent: 80, storageSlots: 100, restHp: 70, restFatigue: 70, bonusInt: 5, bonusLuck: 2, bonusDef: 3, emoji: '🏛️', description: 'Роскошный особняк. Огромные залы и подвалы.' }
};

// Дома Вестероса
const HOUSES_DATA = {
    'Север': { capital:'Винтерфелл', totalAcres:1000000, houses:[
        { id:'stark',name:'Старки',sigil:'🐺',castle:'Винтерфелл',liege:'Старки',status:'Великий Дом',acres:500000 },
        { id:'bolton',name:'Болтоны',sigil:'🩸',castle:'Дредфорт',liege:'Старки',status:'Вассал',acres:200000 }
    ]}
};

// Лошади
const HORSE_TYPES = {
    'work': { name: 'Рабочая лошадь', price: 50, speedBonus: 10, defensePercent: 0, hp: 80, inventorySlots: 5, emoji: '🐴', description: 'Надёжная, но медленная. +5 слотов инвентаря.' },
    'riding': { name: 'Верховая лошадь', price: 150, speedBonus: 25, defensePercent: 2, hp: 100, inventorySlots: 10, emoji: '🏇', description: 'Отличный баланс скорости и выносливости. +10 слотов инвентаря.' },
    'war': { name: 'Боевой конь', price: 400, speedBonus: 20, defensePercent: 5, hp: 150, inventorySlots: 8, emoji: '⚔️', description: 'Смелый и сильный. +8 слотов инвентаря.' },
    'racer': { name: 'Скакун', price: 600, speedBonus: 50, defensePercent: 0, hp: 70, inventorySlots: 3, emoji: '🏃', description: 'Очень быстрый, но хрупкий. +3 слота инвентаря.' },
    'heavy': { name: 'Тяжелый скакун', price: 800, speedBonus: 15, defensePercent: 8, hp: 200, inventorySlots: 15, emoji: '🛡️', description: 'Мощный и выносливый. +15 слотов инвентаря.' },
    'royal': { name: 'Королевский скакун', price: 1500, speedBonus: 40, defensePercent: 6, hp: 180, inventorySlots: 12, emoji: '👑', description: 'Элитный скакун для знати. +12 слотов инвентаря.' },
    'fire': { name: 'Огненный жеребец', price: 3000, speedBonus: 60, defensePercent: 10, hp: 250, inventorySlots: 10, emoji: '🔥', description: 'Легендарный жеребец. Всего 1 в неделю! +10 слотов инвентаря.' }
};

// Портовые города
const PORT_CITIES = {
    'Королевская Гавань': { region: 'Королевские земли', price: 0, emoji: '🏰', description: 'Столица Семи Королевств.' },
    'Винтерфелл': { region: 'Север', price: 100, emoji: '❄️', description: 'Цитадель Севера.' },
    'Кастерли Рок': { region: 'Западные земли', price: 80, emoji: '🦁', description: 'Богатейший город Вестероса.' },
    'Хайгарден': { region: 'Простор', price: 70, emoji: '🌹', description: 'Цветущий город на юге.' },
    'Штормовой Предел': { region: 'Штормовые земли', price: 60, emoji: '🦌', description: 'Крепость Баратеонов.' },
    'Солнечное Копьё': { region: 'Дорн', price: 90, emoji: '☀️', description: 'Столица Дорна.' },
    'Орлиное Гнездо': { region: 'Долина', price: 110, emoji: '🦅', description: 'Неприступная крепость в горах.' },
    'Риверран': { region: 'Речные земли', price: 50, emoji: '🐟', description: 'Сердце Речных земель.' },
    'Пайк': { region: 'Железные острова', price: 120, emoji: '🐙', description: 'Оплот железнорождённых.' }
};

// Все предметы (полный список)
const ALL_ITEMS = {
    weapons: {
        sword: [
            { name:'Деревянный меч', level:1, baseDamage:3 },
            { name:'Ржавый меч', level:5, baseDamage:5 },
            { name:'Короткий меч', level:10, baseDamage:7 },
            { name:'Меч разбойника', level:15, baseDamage:10 },
            { name:'Меч наёмника', level:20, baseDamage:13 },
            { name:'Длинный меч', level:25, baseDamage:16 },
            { name:'Меч стражи', level:30, baseDamage:19 },
            { name:'Стальной меч', level:35, baseDamage:22 },
            { name:'Закалённый меч', level:40, baseDamage:26 },
            { name:'Меч рыцаря', level:45, baseDamage:30 },
            { name:'Меч лорда', level:50, baseDamage:34 },
            { name:'Двуручный меч', level:55, baseDamage:38 },
            { name:'Великий меч', level:60, baseDamage:42 },
            { name:'Меч героя', level:65, baseDamage:46 },
            { name:'Меч чемпиона', level:70, baseDamage:50 },
            { name:'Меч командующего', level:75, baseDamage:55 },
            { name:'Королевский меч', level:80, baseDamage:60 },
            { name:'Меч завоевателя', level:85, baseDamage:65 },
            { name:'Легендарный меч', level:90, baseDamage:70 },
            { name:'Меч судьбы', level:95, baseDamage:75 },
            { name:'Валирийский меч', level:100, baseDamage:90 }
        ],
        spear: [
            { name:'Деревянное копьё', level:1, baseDamage:3 },
            { name:'Ржавое копьё', level:5, baseDamage:5 },
            { name:'Короткое копьё', level:10, baseDamage:7 },
            { name:'Копьё охотника', level:15, baseDamage:9 },
            { name:'Копьё разбойника', level:20, baseDamage:12 },
            { name:'Копьё наёмника', level:25, baseDamage:14 },
            { name:'Копьё стражи', level:30, baseDamage:16 },
            { name:'Копьё рыцаря', level:35, baseDamage:19 },
            { name:'Стальное копьё', level:40, baseDamage:22 },
            { name:'Копьё лорда', level:45, baseDamage:25 },
            { name:'Длинное копьё', level:50, baseDamage:28 },
            { name:'Копьё героя', level:55, baseDamage:32 },
            { name:'Копьё чемпиона', level:60, baseDamage:36 },
            { name:'Копьё командующего', level:65, baseDamage:40 },
            { name:'Королевское копьё', level:70, baseDamage:44 },
            { name:'Копьё завоевателя', level:75, baseDamage:48 },
            { name:'Великое копьё', level:80, baseDamage:52 },
            { name:'Легендарное копьё', level:85, baseDamage:56 },
            { name:'Копьё судьбы', level:90, baseDamage:60 },
            { name:'Копьё бессмертного', level:95, baseDamage:65 },
            { name:'Валирийское копьё', level:100, baseDamage:75 }
        ],
        axe: [
            { name:'Деревянный топор', level:1, baseDamage:4 },
            { name:'Ржавый топор', level:5, baseDamage:6 },
            { name:'Боевой топор', level:10, baseDamage:8 },
            { name:'Топор разбойника', level:15, baseDamage:10 },
            { name:'Топор наёмника', level:20, baseDamage:13 },
            { name:'Топор стражи', level:25, baseDamage:16 },
            { name:'Стальной топор', level:30, baseDamage:19 },
            { name:'Топор рыцаря', level:35, baseDamage:22 },
            { name:'Топор лорда', level:40, baseDamage:26 },
            { name:'Двуручный топор', level:45, baseDamage:30 },
            { name:'Топор героя', level:50, baseDamage:34 },
            { name:'Топор чемпиона', level:55, baseDamage:38 },
            { name:'Топор командующего', level:60, baseDamage:42 },
            { name:'Королевский топор', level:65, baseDamage:46 },
            { name:'Великий топор', level:70, baseDamage:50 },
            { name:'Топор завоевателя', level:75, baseDamage:55 },
            { name:'Легендарный топор', level:80, baseDamage:60 },
            { name:'Топор судьбы', level:85, baseDamage:65 },
            { name:'Топор бессмертного', level:90, baseDamage:70 },
            { name:'Топор бога', level:95, baseDamage:75 },
            { name:'Валирийский топор', level:100, baseDamage:85 }
        ],
        mace: [
            { name:'Деревянная булава', level:1, baseDamage:3 },
            { name:'Ржавая булава', level:5, baseDamage:5 },
            { name:'Булава разбойника', level:10, baseDamage:8 },
            { name:'Булава наёмника', level:15, baseDamage:10 },
            { name:'Булава стражи', level:20, baseDamage:13 },
            { name:'Стальная булава', level:25, baseDamage:16 },
            { name:'Булава рыцаря', level:30, baseDamage:19 },
            { name:'Тяжёлая булава', level:35, baseDamage:22 },
            { name:'Булава лорда', level:40, baseDamage:26 },
            { name:'Булава героя', level:45, baseDamage:30 },
            { name:'Булава чемпиона', level:50, baseDamage:34 },
            { name:'Булава командующего', level:55, baseDamage:38 },
            { name:'Королевская булава', level:60, baseDamage:42 },
            { name:'Великая булава', level:65, baseDamage:46 },
            { name:'Булава завоевателя', level:70, baseDamage:50 },
            { name:'Легендарная булава', level:75, baseDamage:55 },
            { name:'Булава судьбы', level:80, baseDamage:60 },
            { name:'Булава бессмертного', level:85, baseDamage:65 },
            { name:'Булава бога', level:90, baseDamage:70 },
            { name:'Булава властелина', level:95, baseDamage:75 },
            { name:'Валирийская булава', level:100, baseDamage:85 }
        ],
        bow: [
            { name:'Короткий лук', level:1, baseDamage:3 },
            { name:'Охотничий лук', level:5, baseDamage:5 },
            { name:'Лук разбойника', level:10, baseDamage:7 },
            { name:'Лук наёмника', level:15, baseDamage:9 },
            { name:'Лук стражи', level:20, baseDamage:11 },
            { name:'Длинный лук', level:25, baseDamage:13 },
            { name:'Стальной лук', level:30, baseDamage:15 },
            { name:'Лук рыцаря', level:35, baseDamage:18 },
            { name:'Лук лорда', level:40, baseDamage:21 },
            { name:'Лук героя', level:45, baseDamage:24 },
            { name:'Лук чемпиона', level:50, baseDamage:28 },
            { name:'Лук командующего', level:55, baseDamage:32 },
            { name:'Королевский лук', level:60, baseDamage:36 },
            { name:'Великий лук', level:65, baseDamage:40 },
            { name:'Лук завоевателя', level:70, baseDamage:44 },
            { name:'Легендарный лук', level:75, baseDamage:48 },
            { name:'Лук судьбы', level:80, baseDamage:52 },
            { name:'Лук бессмертного', level:85, baseDamage:56 },
            { name:'Лук бога', level:90, baseDamage:60 },
            { name:'Лук властелина', level:95, baseDamage:65 },
            { name:'Валирийский лук', level:100, baseDamage:75 }
        ],
        crossbow: [
            { name:'Лёгкий арбалет', level:5, baseDamage:5 },
            { name:'Арбалет разбойника', level:10, baseDamage:7 },
            { name:'Арбалет наёмника', level:15, baseDamage:9 },
            { name:'Арбалет стражи', level:20, baseDamage:12 },
            { name:'Стальной арбалет', level:25, baseDamage:15 },
            { name:'Арбалет рыцаря', level:30, baseDamage:18 },
            { name:'Тяжёлый арбалет', level:35, baseDamage:21 },
            { name:'Арбалет лорда', level:40, baseDamage:25 },
            { name:'Арбалет героя', level:45, baseDamage:28 },
            { name:'Арбалет чемпиона', level:50, baseDamage:32 },
            { name:'Арбалет командующего', level:55, baseDamage:36 },
            { name:'Королевский арбалет', level:60, baseDamage:40 },
            { name:'Великий арбалет', level:65, baseDamage:44 },
            { name:'Арбалет завоевателя', level:70, baseDamage:48 },
            { name:'Легендарный арбалет', level:75, baseDamage:52 },
            { name:'Арбалет судьбы', level:80, baseDamage:56 },
            { name:'Арбалет бессмертного', level:85, baseDamage:60 },
            { name:'Арбалет бога', level:90, baseDamage:65 },
            { name:'Арбалет властелина', level:95, baseDamage:70 },
            { name:'Валирийский арбалет', level:100, baseDamage:80 }
        ],
        dagger: [
            { name:'Ржавый кинжал', level:1, baseDamage:2 },
            { name:'Кинжал разбойника', level:5, baseDamage:4 },
            { name:'Кинжал наёмника', level:10, baseDamage:6 },
            { name:'Кинжал стражи', level:15, baseDamage:8 },
            { name:'Стальной кинжал', level:20, baseDamage:10 },
            { name:'Кинжал рыцаря', level:25, baseDamage:12 },
            { name:'Кинжал лорда', level:30, baseDamage:14 },
            { name:'Кинжал героя', level:35, baseDamage:16 },
            { name:'Кинжал чемпиона', level:40, baseDamage:18 },
            { name:'Кинжал командующего', level:45, baseDamage:20 },
            { name:'Королевский кинжал', level:50, baseDamage:22 },
            { name:'Великий кинжал', level:55, baseDamage:24 },
            { name:'Кинжал завоевателя', level:60, baseDamage:26 },
            { name:'Легендарный кинжал', level:65, baseDamage:28 },
            { name:'Кинжал судьбы', level:70, baseDamage:30 },
            { name:'Кинжал бессмертного', level:75, baseDamage:32 },
            { name:'Кинжал бога', level:80, baseDamage:34 },
            { name:'Кинжал драконоборца', level:85, baseDamage:36 },
            { name:'Кинжал властелина', level:90, baseDamage:38 },
            { name:'Кинжал легенды', level:95, baseDamage:40 },
            { name:'Валирийский кинжал', level:100, baseDamage:50 }
        ],
        shield: [
            { name:'Деревянный щит', level:1, defense:2 },
            { name:'Кожаный щит', level:5, defense:4 },
            { name:'Щит разбойника', level:10, defense:6 },
            { name:'Щит наёмника', level:15, defense:8 },
            { name:'Щит стражи', level:20, defense:10 },
            { name:'Стальной щит', level:25, defense:12 },
            { name:'Щит рыцаря', level:30, defense:14 },
            { name:'Щит лорда', level:35, defense:16 },
            { name:'Щит героя', level:40, defense:18 },
            { name:'Щит чемпиона', level:45, defense:20 },
            { name:'Щит командующего', level:50, defense:22 },
            { name:'Королевский щит', level:55, defense:24 },
            { name:'Великий щит', level:60, defense:26 },
            { name:'Щит завоевателя', level:65, defense:28 },
            { name:'Легендарный щит', level:70, defense:30 },
            { name:'Щит судьбы', level:75, defense:32 },
            { name:'Щит бессмертного', level:80, defense:34 },
            { name:'Щит бога', level:85, defense:36 },
            { name:'Щит властелина', level:90, defense:38 },
            { name:'Щит драконоборца', level:95, defense:40 },
            { name:'Валирийский щит', level:100, defense:50 }
        ]
    },
    leather: {
        helmet: [
            { name:'Рваный кожаный шлем', level:1, baseDefense:1 },
            { name:'Плохой кожаный шлем', level:5, baseDefense:2 },
            { name:'Кожаный шлем', level:10, baseDefense:3 },
            { name:'Кожаный шлем разбойника', level:15, baseDefense:5 },
            { name:'Кожаный шлем наёмника', level:20, baseDefense:7 },
            { name:'Кожаный шлем стражи', level:25, baseDefense:9 },
            { name:'Кожаный шлем рыцаря', level:30, baseDefense:11 },
            { name:'Кожаный шлем лорда', level:35, baseDefense:13 },
            { name:'Кожаный шлем героя', level:40, baseDefense:15 },
            { name:'Кожаный шлем чемпиона', level:45, baseDefense:17 },
            { name:'Кожаный шлем командующего', level:50, baseDefense:19 },
            { name:'Королевский кожаный шлем', level:55, baseDefense:21 },
            { name:'Великий кожаный шлем', level:60, baseDefense:23 },
            { name:'Кожаный шлем завоевателя', level:65, baseDefense:25 },
            { name:'Легендарный кожаный шлем', level:70, baseDefense:27 },
            { name:'Кожаный шлем судьбы', level:75, baseDefense:29 },
            { name:'Кожаный шлем бессмертного', level:80, baseDefense:31 },
            { name:'Кожаный шлем бога', level:85, baseDefense:33 },
            { name:'Кожаный шлем властелина', level:90, baseDefense:35 },
            { name:'Кожаный шлем драконоборца', level:95, baseDefense:37 },
            { name:'Валирийский кожаный шлем', level:100, baseDefense:50 }
        ],
        chestplate: [
            { name:'Рваный кожаный нагрудник', level:1, baseDefense:1 },
            { name:'Плохой кожаный нагрудник', level:5, baseDefense:3 },
            { name:'Кожаный нагрудник', level:10, baseDefense:5 },
            { name:'Кожаный нагрудник разбойника', level:15, baseDefense:8 },
            { name:'Кожаный нагрудник наёмника', level:20, baseDefense:11 },
            { name:'Кожаный нагрудник стражи', level:25, baseDefense:14 },
            { name:'Кожаный нагрудник рыцаря', level:30, baseDefense:17 },
            { name:'Кожаный нагрудник лорда', level:35, baseDefense:20 },
            { name:'Кожаный нагрудник героя', level:40, baseDefense:23 },
            { name:'Кожаный нагрудник чемпиона', level:45, baseDefense:26 },
            { name:'Кожаный нагрудник командующего', level:50, baseDefense:29 },
            { name:'Королевский кожаный нагрудник', level:55, baseDefense:32 },
            { name:'Великий кожаный нагрудник', level:60, baseDefense:35 },
            { name:'Кожаный нагрудник завоевателя', level:65, baseDefense:38 },
            { name:'Легендарный кожаный нагрудник', level:70, baseDefense:41 },
            { name:'Кожаный нагрудник судьбы', level:75, baseDefense:44 },
            { name:'Кожаный нагрудник бессмертного', level:80, baseDefense:47 },
            { name:'Кожаный нагрудник бога', level:85, baseDefense:50 },
            { name:'Кожаный нагрудник властелина', level:90, baseDefense:53 },
            { name:'Кожаный нагрудник драконоборца', level:95, baseDefense:56 },
            { name:'Валирийский кожаный нагрудник', level:100, baseDefense:70 }
        ],
        boots: [
            { name:'Рваные кожаные сапоги', level:1, baseDefense:0, speedPercent: 1 },
            { name:'Плохие кожаные сапоги', level:5, baseDefense:1, speedPercent: 2 },
            { name:'Кожаные сапоги', level:10, baseDefense:2, speedPercent: 3 },
            { name:'Сапоги разбойника', level:15, baseDefense:3, speedPercent: 5 },
            { name:'Сапоги наёмника', level:20, baseDefense:4, speedPercent: 7 },
            { name:'Сапоги стражи', level:25, baseDefense:5, speedPercent: 9 },
            { name:'Сапоги рыцаря', level:30, baseDefense:6, speedPercent: 11 },
            { name:'Сапоги лорда', level:35, baseDefense:7, speedPercent: 13 },
            { name:'Сапоги героя', level:40, baseDefense:8, speedPercent: 15 },
            { name:'Сапоги чемпиона', level:45, baseDefense:9, speedPercent: 17 },
            { name:'Сапоги командующего', level:50, baseDefense:10, speedPercent: 19 },
            { name:'Королевские сапоги', level:55, baseDefense:11, speedPercent: 21 },
            { name:'Великие сапоги', level:60, baseDefense:12, speedPercent: 23 },
            { name:'Сапоги завоевателя', level:65, baseDefense:13, speedPercent: 25 },
            { name:'Легендарные сапоги', level:70, baseDefense:14, speedPercent: 27 },
            { name:'Сапоги судьбы', level:75, baseDefense:15, speedPercent: 29 },
            { name:'Сапоги бессмертного', level:80, baseDefense:16, speedPercent: 30 },
            { name:'Сапоги бога', level:85, baseDefense:17, speedPercent: 30 },
            { name:'Сапоги властелина', level:90, baseDefense:18, speedPercent: 30 },
            { name:'Сапоги драконоборца', level:95, baseDefense:19, speedPercent: 30 },
            { name:'Валирийские сапоги', level:100, baseDefense:30, speedPercent: 30 }
        ],
        shoulders: [
            { name:'Рваные кожаные наплечники', level:1, baseDefense:0 },
            { name:'Плохие кожаные наплечники', level:5, baseDefense:1 },
            { name:'Кожаные наплечники', level:10, baseDefense:2 },
            { name:'Наплечники разбойника', level:15, baseDefense:3 },
            { name:'Наплечники наёмника', level:20, baseDefense:4 },
            { name:'Наплечники стражи', level:25, baseDefense:5 },
            { name:'Наплечники рыцаря', level:30, baseDefense:6 },
            { name:'Наплечники лорда', level:35, baseDefense:7 },
            { name:'Наплечники героя', level:40, baseDefense:8 },
            { name:'Наплечники чемпиона', level:45, baseDefense:9 },
            { name:'Наплечники командующего', level:50, baseDefense:10 },
            { name:'Королевские наплечники', level:55, baseDefense:11 },
            { name:'Великие наплечники', level:60, baseDefense:12 },
            { name:'Наплечники завоевателя', level:65, baseDefense:13 },
            { name:'Легендарные наплечники', level:70, baseDefense:14 },
            { name:'Наплечники судьбы', level:75, baseDefense:15 },
            { name:'Наплечники бессмертного', level:80, baseDefense:16 },
            { name:'Наплечники бога', level:85, baseDefense:17 },
            { name:'Наплечники властелина', level:90, baseDefense:18 },
            { name:'Наплечники драконоборца', level:95, baseDefense:19 },
            { name:'Валирийские наплечники', level:100, baseDefense:30 }
        ],
        leggings: [
            { name:'Рваные кожаные поножи', level:1, baseDefense:0 },
            { name:'Плохие кожаные поножи', level:5, baseDefense:1 },
            { name:'Кожаные поножи', level:10, baseDefense:2 },
            { name:'Поножи разбойника', level:15, baseDefense:3 },
            { name:'Поножи наёмника', level:20, baseDefense:4 },
            { name:'Поножи стражи', level:25, baseDefense:5 },
            { name:'Поножи рыцаря', level:30, baseDefense:6 },
            { name:'Поножи лорда', level:35, baseDefense:7 },
            { name:'Поножи героя', level:40, baseDefense:8 },
            { name:'Поножи чемпиона', level:45, baseDefense:9 },
            { name:'Поножи командующего', level:50, baseDefense:10 },
            { name:'Королевские поножи', level:55, baseDefense:11 },
            { name:'Великие поножи', level:60, baseDefense:12 },
            { name:'Поножи завоевателя', level:65, baseDefense:13 },
            { name:'Легендарные поножи', level:70, baseDefense:14 },
            { name:'Поножи судьбы', level:75, baseDefense:15 },
            { name:'Поножи бессмертного', level:80, baseDefense:16 },
            { name:'Поножи бога', level:85, baseDefense:17 },
            { name:'Поножи властелина', level:90, baseDefense:18 },
            { name:'Поножи драконоборца', level:95, baseDefense:19 },
            { name:'Валирийские поножи', level:100, baseDefense:30 }
        ],
        gloves: [
            { name:'Рваные кожаные перчатки', level:1, baseDefense:0 },
            { name:'Плохие кожаные перчатки', level:5, baseDefense:1 },
            { name:'Кожаные перчатки', level:10, baseDefense:2 },
            { name:'Перчатки разбойника', level:15, baseDefense:3 },
            { name:'Перчатки наёмника', level:20, baseDefense:4 },
            { name:'Перчатки стражи', level:25, baseDefense:5 },
            { name:'Перчатки рыцаря', level:30, baseDefense:6 },
            { name:'Перчатки лорда', level:35, baseDefense:7 },
            { name:'Перчатки героя', level:40, baseDefense:8 },
            { name:'Перчатки чемпиона', level:45, baseDefense:9 },
            { name:'Перчатки командующего', level:50, baseDefense:10 },
            { name:'Королевские перчатки', level:55, baseDefense:11 },
            { name:'Великие перчатки', level:60, baseDefense:12 },
            { name:'Перчатки завоевателя', level:65, baseDefense:13 },
            { name:'Легендарные перчатки', level:70, baseDefense:14 },
            { name:'Перчатки судьбы', level:75, baseDefense:15 },
            { name:'Перчатки бессмертного', level:80, baseDefense:16 },
            { name:'Перчатки бога', level:85, baseDefense:17 },
            { name:'Перчатки властелина', level:90, baseDefense:18 },
            { name:'Перчатки драконоборца', level:95, baseDefense:19 },
            { name:'Валирийские перчатки', level:100, baseDefense:30 }
        ],
        belt: [
            { name:'Рваный кожаный пояс', level:1, baseDefense:0 },
            { name:'Плохой кожаный пояс', level:5, baseDefense:1 },
            { name:'Кожаный пояс', level:10, baseDefense:2 },
            { name:'Пояс разбойника', level:15, baseDefense:3 },
            { name:'Пояс наёмника', level:20, baseDefense:4 },
            { name:'Пояс стражи', level:25, baseDefense:5 },
            { name:'Пояс рыцаря', level:30, baseDefense:6 },
            { name:'Пояс лорда', level:35, baseDefense:7 },
            { name:'Пояс героя', level:40, baseDefense:8 },
            { name:'Пояс чемпиона', level:45, baseDefense:9 },
            { name:'Пояс командующего', level:50, baseDefense:10 },
            { name:'Королевский пояс', level:55, baseDefense:11 },
            { name:'Великий пояс', level:60, baseDefense:12 },
            { name:'Пояс завоевателя', level:65, baseDefense:13 },
            { name:'Легендарный пояс', level:70, baseDefense:14 },
            { name:'Пояс судьбы', level:75, baseDefense:15 },
            { name:'Пояс бессмертного', level:80, baseDefense:16 },
            { name:'Пояс бога', level:85, baseDefense:17 },
            { name:'Пояс властелина', level:90, baseDefense:18 },
            { name:'Пояс драконоборца', level:95, baseDefense:19 },
            { name:'Валирийский пояс', level:100, baseDefense:30 }
        ],
        cloak: [
            { name:'Рваный кожаный плащ', level:1, baseDefense:0 },
            { name:'Плохой кожаный плащ', level:5, baseDefense:1 },
            { name:'Кожаный плащ', level:10, baseDefense:2 },
            { name:'Плащ разбойника', level:15, baseDefense:3 },
            { name:'Плащ наёмника', level:20, baseDefense:4 },
            { name:'Плащ стражи', level:25, baseDefense:5 },
            { name:'Плащ рыцаря', level:30, baseDefense:6 },
            { name:'Плащ лорда', level:35, baseDefense:7 },
            { name:'Плащ героя', level:40, baseDefense:8 },
            { name:'Плащ чемпиона', level:45, baseDefense:9 },
            { name:'Плащ командующего', level:50, baseDefense:10 },
            { name:'Королевский плащ', level:55, baseDefense:11 },
            { name:'Великий плащ', level:60, baseDefense:12 },
            { name:'Плащ завоевателя', level:65, baseDefense:13 },
            { name:'Легендарный плащ', level:70, baseDefense:14 },
            { name:'Плащ судьбы', level:75, baseDefense:15 },
            { name:'Плащ бессмертного', level:80, baseDefense:16 },
            { name:'Плащ бога', level:85, baseDefense:17 },
            { name:'Плащ властелина', level:90, baseDefense:18 },
            { name:'Плащ драконоборца', level:95, baseDefense:19 },
            { name:'Валирийский плащ', level:100, baseDefense:30 }
        ]
    },
    plate: {
        helmet: [
            { name:'Ржавый латный шлем', level:5, baseDefense:3 },
            { name:'Латный шлем', level:10, baseDefense:5 },
            { name:'Латный шлем разбойника', level:15, baseDefense:7 },
            { name:'Латный шлем наёмника', level:20, baseDefense:9 },
            { name:'Латный шлем стражи', level:25, baseDefense:11 },
            { name:'Латный шлем рыцаря', level:30, baseDefense:13 },
            { name:'Латный шлем лорда', level:35, baseDefense:15 },
            { name:'Латный шлем героя', level:40, baseDefense:17 },
            { name:'Латный шлем чемпиона', level:45, baseDefense:19 },
            { name:'Латный шлем командующего', level:50, baseDefense:21 },
            { name:'Королевский латный шлем', level:55, baseDefense:23 },
            { name:'Великий латный шлем', level:60, baseDefense:25 },
            { name:'Латный шлем завоевателя', level:65, baseDefense:27 },
            { name:'Легендарный латный шлем', level:70, baseDefense:29 },
            { name:'Латный шлем судьбы', level:75, baseDefense:31 },
            { name:'Латный шлем бессмертного', level:80, baseDefense:33 },
            { name:'Латный шлем бога', level:85, baseDefense:35 },
            { name:'Латный шлем властелина', level:90, baseDefense:37 },
            { name:'Латный шлем легенды', level:95, baseDefense:39 },
            { name:'Валирийский латный шлем', level:100, baseDefense:50 }
        ],
        chestplate: [
            { name:'Ржавый латный нагрудник', level:5, baseDefense:4 },
            { name:'Латный нагрудник', level:10, baseDefense:8 },
            { name:'Латный нагрудник разбойника', level:15, baseDefense:12 },
            { name:'Латный нагрудник наёмника', level:20, baseDefense:16 },
            { name:'Латный нагрудник стражи', level:25, baseDefense:20 },
            { name:'Латный нагрудник рыцаря', level:30, baseDefense:24 },
            { name:'Латный нагрудник лорда', level:35, baseDefense:28 },
            { name:'Латный нагрудник героя', level:40, baseDefense:32 },
            { name:'Латный нагрудник чемпиона', level:45, baseDefense:36 },
            { name:'Латный нагрудник командующего', level:50, baseDefense:40 },
            { name:'Королевский латный нагрудник', level:55, baseDefense:44 },
            { name:'Великий латный нагрудник', level:60, baseDefense:48 },
            { name:'Латный нагрудник завоевателя', level:65, baseDefense:52 },
            { name:'Легендарный латный нагрудник', level:70, baseDefense:56 },
            { name:'Латный нагрудник судьбы', level:75, baseDefense:60 },
            { name:'Латный нагрудник бессмертного', level:80, baseDefense:64 },
            { name:'Латный нагрудник бога', level:85, baseDefense:68 },
            { name:'Латный нагрудник властелина', level:90, baseDefense:72 },
            { name:'Латный нагрудник легенды', level:95, baseDefense:76 },
            { name:'Валирийский латный нагрудник', level:100, baseDefense:90 }
        ],
        boots: [
            { name:'Ржавые латные сапоги', level:5, baseDefense:2, speedPercent: 1 },
            { name:'Латные сапоги', level:10, baseDefense:4, speedPercent: 2 },
            { name:'Латные сапоги разбойника', level:15, baseDefense:6, speedPercent: 3 },
            { name:'Латные сапоги наёмника', level:20, baseDefense:8, speedPercent: 4 },
            { name:'Латные сапоги стражи', level:25, baseDefense:10, speedPercent: 5 },
            { name:'Латные сапоги рыцаря', level:30, baseDefense:12, speedPercent: 6 },
            { name:'Латные сапоги лорда', level:35, baseDefense:14, speedPercent: 7 },
            { name:'Латные сапоги героя', level:40, baseDefense:16, speedPercent: 8 },
            { name:'Латные сапоги чемпиона', level:45, baseDefense:18, speedPercent: 9 },
            { name:'Латные сапоги командующего', level:50, baseDefense:20, speedPercent: 10 },
            { name:'Королевские латные сапоги', level:55, baseDefense:22, speedPercent: 11 },
            { name:'Великие латные сапоги', level:60, baseDefense:24, speedPercent: 12 },
            { name:'Латные сапоги завоевателя', level:65, baseDefense:26, speedPercent: 13 },
            { name:'Легендарные латные сапоги', level:70, baseDefense:28, speedPercent: 14 },
            { name:'Латные сапоги судьбы', level:75, baseDefense:30, speedPercent: 15 },
            { name:'Латные сапоги бессмертного', level:80, baseDefense:32, speedPercent: 15 },
            { name:'Латные сапоги бога', level:85, baseDefense:34, speedPercent: 15 },
            { name:'Латные сапоги властелина', level:90, baseDefense:36, speedPercent: 15 },
            { name:'Латные сапоги легенды', level:95, baseDefense:38, speedPercent: 15 },
            { name:'Валирийские латные сапоги', level:100, baseDefense:45, speedPercent: 15 }
        ],
        shoulders: [
            { name:'Ржавые латные наплечники', level:5, baseDefense:2 },
            { name:'Латные наплечники', level:10, baseDefense:4 },
            { name:'Латные наплечники разбойника', level:15, baseDefense:6 },
            { name:'Латные наплечники наёмника', level:20, baseDefense:8 },
            { name:'Латные наплечники стражи', level:25, baseDefense:10 },
            { name:'Латные наплечники рыцаря', level:30, baseDefense:12 },
            { name:'Латные наплечники лорда', level:35, baseDefense:14 },
            { name:'Латные наплечники героя', level:40, baseDefense:16 },
            { name:'Латные наплечники чемпиона', level:45, baseDefense:18 },
            { name:'Латные наплечники командующего', level:50, baseDefense:20 },
            { name:'Королевские латные наплечники', level:55, baseDefense:22 },
            { name:'Великие латные наплечники', level:60, baseDefense:24 },
            { name:'Латные наплечники завоевателя', level:65, baseDefense:26 },
            { name:'Легендарные латные наплечники', level:70, baseDefense:28 },
            { name:'Латные наплечники судьбы', level:75, baseDefense:30 },
            { name:'Латные наплечники бессмертного', level:80, baseDefense:32 },
            { name:'Латные наплечники бога', level:85, baseDefense:34 },
            { name:'Латные наплечники властелина', level:90, baseDefense:36 },
            { name:'Латные наплечники легенды', level:95, baseDefense:38 },
            { name:'Валирийские латные наплечники', level:100, baseDefense:50 }
        ],
        leggings: [
            { name:'Ржавые латные поножи', level:5, baseDefense:2 },
            { name:'Латные поножи', level:10, baseDefense:4 },
            { name:'Латные поножи разбойника', level:15, baseDefense:6 },
            { name:'Латные поножи наёмника', level:20, baseDefense:8 },
            { name:'Латные поножи стражи', level:25, baseDefense:10 },
            { name:'Латные поножи рыцаря', level:30, baseDefense:12 },
            { name:'Латные поножи лорда', level:35, baseDefense:14 },
            { name:'Латные поножи героя', level:40, baseDefense:16 },
            { name:'Латные поножи чемпиона', level:45, baseDefense:18 },
            { name:'Латные поножи командующего', level:50, baseDefense:20 },
            { name:'Королевские латные поножи', level:55, baseDefense:22 },
            { name:'Великие латные поножи', level:60, baseDefense:24 },
            { name:'Латные поножи завоевателя', level:65, baseDefense:26 },
            { name:'Легендарные латные поножи', level:70, baseDefense:28 },
            { name:'Латные поножи судьбы', level:75, baseDefense:30 },
            { name:'Латные поножи бессмертного', level:80, baseDefense:32 },
            { name:'Латные поножи бога', level:85, baseDefense:34 },
            { name:'Латные поножи властелина', level:90, baseDefense:36 },
            { name:'Латные поножи легенды', level:95, baseDefense:38 },
            { name:'Валирийские латные поножи', level:100, baseDefense:50 }
        ],
        gloves: [
            { name:'Ржавые латные перчатки', level:5, baseDefense:2 },
            { name:'Латные перчатки', level:10, baseDefense:4 },
            { name:'Латные перчатки разбойника', level:15, baseDefense:6 },
            { name:'Латные перчатки наёмника', level:20, baseDefense:8 },
            { name:'Латные перчатки стражи', level:25, baseDefense:10 },
            { name:'Латные перчатки рыцаря', level:30, baseDefense:12 },
            { name:'Латные перчатки лорда', level:35, baseDefense:14 },
            { name:'Латные перчатки героя', level:40, baseDefense:16 },
            { name:'Латные перчатки чемпиона', level:45, baseDefense:18 },
            { name:'Латные перчатки командующего', level:50, baseDefense:20 },
            { name:'Королевские латные перчатки', level:55, baseDefense:22 },
            { name:'Великие латные перчатки', level:60, baseDefense:24 },
            { name:'Латные перчатки завоевателя', level:65, baseDefense:26 },
            { name:'Легендарные латные перчатки', level:70, baseDefense:28 },
            { name:'Латные перчатки судьбы', level:75, baseDefense:30 },
            { name:'Латные перчатки бессмертного', level:80, baseDefense:32 },
            { name:'Латные перчатки бога', level:85, baseDefense:34 },
            { name:'Латные перчатки властелина', level:90, baseDefense:36 },
            { name:'Латные перчатки легенды', level:95, baseDefense:38 },
            { name:'Валирийские латные перчатки', level:100, baseDefense:50 }
        ],
        belt: [
            { name:'Ржавый латный пояс', level:5, baseDefense:2 },
            { name:'Латный пояс', level:10, baseDefense:4 },
            { name:'Латный пояс разбойника', level:15, baseDefense:6 },
            { name:'Латный пояс наёмника', level:20, baseDefense:8 },
            { name:'Латный пояс стражи', level:25, baseDefense:10 },
            { name:'Латный пояс рыцаря', level:30, baseDefense:12 },
            { name:'Латный пояс лорда', level:35, baseDefense:14 },
            { name:'Латный пояс героя', level:40, baseDefense:16 },
            { name:'Латный пояс чемпиона', level:45, baseDefense:18 },
            { name:'Латный пояс командующего', level:50, baseDefense:20 },
            { name:'Королевский латный пояс', level:55, baseDefense:22 },
            { name:'Великий латный пояс', level:60, baseDefense:24 },
            { name:'Латный пояс завоевателя', level:65, baseDefense:26 },
            { name:'Легендарный латный пояс', level:70, baseDefense:28 },
            { name:'Латный пояс судьбы', level:75, baseDefense:30 },
            { name:'Латный пояс бессмертного', level:80, baseDefense:32 },
            { name:'Латный пояс бога', level:85, baseDefense:34 },
            { name:'Латный пояс властелина', level:90, baseDefense:36 },
            { name:'Латный пояс легенды', level:95, baseDefense:38 },
            { name:'Валирийский латный пояс', level:100, baseDefense:50 }
        ],
        cloak: [
            { name:'Ржавый латный плащ', level:5, baseDefense:2 },
            { name:'Латный плащ', level:10, baseDefense:4 },
            { name:'Латный плащ разбойника', level:15, baseDefense:6 },
            { name:'Латный плащ наёмника', level:20, baseDefense:8 },
            { name:'Латный плащ стражи', level:25, baseDefense:10 },
            { name:'Латный плащ рыцаря', level:30, baseDefense:12 },
            { name:'Латный плащ лорда', level:35, baseDefense:14 },
            { name:'Латный плащ героя', level:40, baseDefense:16 },
            { name:'Латный плащ чемпиона', level:45, baseDefense:18 },
            { name:'Латный плащ командующего', level:50, baseDefense:20 },
            { name:'Королевский латный плащ', level:55, baseDefense:22 },
            { name:'Великий латный плащ', level:60, baseDefense:24 },
            { name:'Латный плащ завоевателя', level:65, baseDefense:26 },
            { name:'Легендарный латный плащ', level:70, baseDefense:28 },
            { name:'Латный плащ судьбы', level:75, baseDefense:30 },
            { name:'Латный плащ бессмертного', level:80, baseDefense:32 },
            { name:'Латный плащ бога', level:85, baseDefense:34 },
            { name:'Латный плащ властелина', level:90, baseDefense:36 },
            { name:'Латный плащ легенды', level:95, baseDefense:38 },
            { name:'Валирийский латный плащ', level:100, baseDefense:50 }
        ]
    }
};
